# permissions to do edit applicationgenerators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationgenerator-editor-role
rules:
- apiGroups:
  - appgenerator.rm-rf.ca
  resources:
  - applicationgenerators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appgenerator.rm-rf.ca
  resources:
  - applicationgenerators/status
  verbs:
  - get
  - patch
  - update
